alias cp='cp -i'
alias egrep='egrep --color=always'
alias fgrep='fgrep --color=always'
alias grep='grep --color=always'
alias l.='ls -d .* --color=always'
alias ll='ls -lha --color=always'
alias ls='ls --color=always'
alias mv='mv -i'
alias rm='rm -i'
